definitions:
  model.SwaggerProject:
    properties:
      createAt:
        type: string
      id:
        type: string
      name:
        maxLength: 500
        minLength: 2
        type: string
      updateAt:
        type: string
    required:
    - name
    type: object
  model.SwaggerProjects:
    properties:
      data:
        items:
          $ref: '#/definitions/model.SwaggerProject'
        type: array
      pager:
        $ref: '#/definitions/pkg.Pager'
    type: object
  pkg.Error:
    properties:
      code:
        type: integer
      details:
        items:
          type: string
        type: array
      msg:
        type: string
    type: object
  pkg.Pager:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      total_rows:
        type: integer
    type: object
info:
  contact: {}
  title: TrackMaster
  version: "1.0"
paths:
  /api/v1/projects:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            items:
              $ref: '#/definitions/model.SwaggerProjects'
            type: array
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/pkg.Error'
      tags:
      - project
  /api/v1/sync-projects:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: object
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/pkg.Error'
      tags:
      - project
swagger: "2.0"
