definitions:
  model.Account:
    properties:
      createdAt:
        type: string
      description:
        maxLength: 50
        minLength: 2
        type: string
      id:
        maxLength: 32
        type: string
      projectID:
        maxLength: 32
        type: string
      updatedAt:
        type: string
    required:
    - description
    - id
    - projectID
    type: object
  model.Accounts:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Account'
        type: array
      pager:
        $ref: '#/definitions/pkg.Pager'
    type: object
  model.Project:
    properties:
      createdAt:
        type: string
      id:
        type: string
      name:
        maxLength: 500
        minLength: 2
        type: string
      updatedAt:
        type: string
    required:
    - name
    type: object
  model.Projects:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Project'
        type: array
      pager:
        $ref: '#/definitions/pkg.Pager'
    type: object
  model.Story:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        maxLength: 32
        type: string
      name:
        maxLength: 50
        minLength: 2
        type: string
      projectID:
        maxLength: 32
        type: string
      updatedAt:
        type: string
    required:
    - id
    - name
    - projectID
    type: object
  pkg.Error:
    properties:
      code:
        type: integer
      details:
        items:
          type: string
        type: array
      msg:
        type: string
    type: object
  pkg.Pager:
    properties:
      page:
        type: integer
      pageSize:
        type: integer
      totalRow:
        type: integer
    type: object
info:
  contact: {}
  title: TrackMaster
  version: "1.0"
paths:
  /api/v1/accounts:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: string
      - description: page size
        in: query
        name: pageSize
        type: string
      - description: description
        in: query
        name: description
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            items:
              $ref: '#/definitions/model.Accounts'
            type: array
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/pkg.Error'
      tags:
      - account
    post:
      parameters:
      - description: page
        in: body
        name: projectID
        required: true
        schema:
          type: string
      - description: page size
        in: body
        name: id
        required: true
        schema:
          type: string
      - description: description
        in: body
        name: description
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            items:
              $ref: '#/definitions/model.Account'
            type: array
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/pkg.Error'
      tags:
      - account
  /api/v1/accounts/{id}:
    delete:
      parameters:
      - description: account id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: object
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/pkg.Error'
      tags:
      - account
  /api/v1/projects:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            items:
              $ref: '#/definitions/model.Projects'
            type: array
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/pkg.Error'
      tags:
      - project
  /api/v1/projects/sync:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: object
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/pkg.Error'
      tags:
      - project
  /api/v1/stories/sync:
    post:
      parameters:
      - description: project id
        in: query
        name: project
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            items:
              $ref: '#/definitions/model.Story'
            type: array
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/pkg.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/pkg.Error'
      tags:
      - story
swagger: "2.0"
